POST http://localhost:5000/https://q-delivery.herokuapp.com/regidter HTTP/1.1 
content-type: application/json

{
    "Name": "Eduard", 
    "Role": "admin",
    "Password": "qweasdzxc"
}

###

GET http://localhost:5000/events/620f8c0e6fe01d0d95b044bc HTTP/1.1 
content-type: application/json