POST http://localhost:5000/users HTTP/1.1 
content-type: application/json

{
    "name": "Test", 
    "email": "test@test.com"
}

###
GET http://localhost:3000/users HTTP/1.1 
content-type: application/json

###
GET http://localhost:3000/users/620be2980af88ad63ff9bcb9 HTTP/1.1 
content-type: application/json

###
DELETE http://localhost:3000/users/620be2980af88ad63ff9bcb9 HTTP/1.1 

###
PATCH http://localhost:3000/users/620be617a99af22bc3b0ec50 HTTP/1.1
content-type: application/json 

{
    "name": "11111", 
    "email": "22222"
}
